FROM ruby:2.5.9-stretch

# Reemplazar las sources.list obsoletas con las de archive.debian.org,
# actualizar e instalar dependencias.
ENV DEBIAN_FRONTEND noninteractive
RUN echo "deb http://archive.debian.org/debian/ stretch contrib main non-free" > /etc/apt/sources.list
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
      shared-mime-info \
      libpq-dev \
      libsodium-dev \
      nodejs

# Usar el mismo workdir que vamos a montar en el compose.
WORKDIR /home/app/

# Instalar gemas.
COPY --chown=app:app Gemfile Gemfile.lock .
# Ignorar documentación.
# Ignorar entornos no de producción.
RUN echo 'gem: --no-rdoc --no-ri' >> ~/.gemrc && \
    gem install bundler:1.17.3 && \
    bundle install

CMD ["bin/start"]
