name: sisinta

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - db
    restart: always
  db:
    # image: postgres:9.1.24
    image: mdillon/postgis:9.1
    ports:
      - 5432:5432
    env_file:
      - .env
