name: sisinta

services:
  db:
    image: mdillon/postgis:9.1
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    build:
      context: .
      args:
        # Necesario porque la configuración de precompilado de assets usa 'production'.
        - RAILS_ENV=${RAILS_ENV}
        - MEMCACHE_SERVERS=${MEMCACHE_SERVERS}
        - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    ports:
      - 9292:9292
    env_file:
      - .env
    depends_on:
      - memcached
      - db
    restart: always
  web:
    build:
      context: nginx
    ports:
      - 80:80
    depends_on:
      - app
    restart: always
    read_only: true
    volumes:
      # Habilitar estos volúmenes permite montar el container como read_only
      - ${PWD}/tmp/nginx/cache:/var/cache/nginx
      - ${PWD}/tmp/nginx/pid:/var/run
    volumes_from:
      # Dar acceso a los volúmenes que define 'app', para servir los assets.
      - app:ro
  memcached:
    image: memcached
    command:
      - --conn-limit=${MEMCACHED_CONN_LIMIT}
      - --memory-limit=${MEMCACHED_MEMORY_LIMIT}
      - --threads=${MEMCACHED_THREADS}
    ports:
      - 11211:11211
volumes:
  db-data:
