# PostgreSQL 9.1.24
#
# Usamos activerecord-postgis-adapter como adaptador, que maneja la información
# geoespacial. Se crea una aplicación normal con postgresql y se cambia de
# adaptador. El template es un template especial a usar cuando se crean las
# bases de datos (en vez del default template1, que tiene cargadas las tablas
# de PostGIS, cuyo propietario tiene que ser el mismo username de la aplicación
# rails (o sea lo mismo que username en esta configuración).

# Configuración default
default: &default
  adapter: postgis
  template: template_postgis
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  database: <%= ENV['POSTGRES_DB'] %>

development:
  <<: *default
  min_messages: WARNING

test:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>_test
  min_messages: WARNING

production:
  <<: *default
