development:
  secret_key_base: '3d04c4af09240ae9210e7f61279f08cccfeffc6541e83f31b0c0bcb00a9619041c6388e0c1bfff207f7e4354fd184cb1a667008662ebc4ea0c19e19b14585d05'
  google_api_key: <%= ENV['GOOGLE_API_KEY'] %>
  mail_de_contacto: 'sisinta@dev'

test:
  secret_key_base: '3d04c4af09240ae9210e7f61279f08cccfeffc6541e83f31b0c0bcb00a9619041c6388e0c1bfff207f7e4354fd184cb1a667008662ebc4ea0c19e19b14585d05'
  google_api_key: <%= ENV['GOOGLE_API_KEY'] %>
  mail_de_contacto: 'sisinta@test'

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  google_api_key: <%= ENV['GOOGLE_API_KEY'] %>
  mail_de_contacto: <%= ENV['SISAR_MAIL_DE_CONTACTO'] %>
